// Copyright (c) 2026 Alvin Wilsen Chan Chua
// GitHub: chuaalvw-y
// Licensed under the Alvin Wilsen Chan Chua Proprietary Use-Only License.
// See LICENSE.txt in the project root for full license information.

using System.ComponentModel.DataAnnotations;
using ChuA.Testing.Constants;

namespace ChuA.Testing.Configuration;

/// <summary>
/// Provides strongly typed configuration for ChuA testing infrastructure.
/// </summary>
public sealed class ChuATestingOptions
{
    /// <summary>
    /// Gets or sets a value indicating whether deterministic values should be generated by default.
    /// </summary>
    public bool UseDeterministicValues { get; set; } = true;

    /// <summary>
    /// Gets or sets the deterministic seed used by builders and providers.
    /// </summary>
    [Range(1, int.MaxValue)]
    public int Seed { get; set; } = ChuATestingDefaults.Seed;

    /// <summary>
    /// Gets or sets the fixed UTC clock value used by the default test clock when deterministic values are enabled.
    /// </summary>
    public DateTimeOffset ClockUtcNow { get; set; } = ChuATestingDefaults.ClockUtcNow;

    /// <summary>
    /// Gets or sets the default timeout used by test infrastructure.
    /// </summary>
    [Range(typeof(TimeSpan), "00:00:00.001", "1.00:00:00")]
    public TimeSpan DefaultTimeout { get; set; } = ChuATestingDefaults.Timeout;

    /// <summary>
    /// Gets or sets a value indicating whether fake HTTP handlers should throw when no route matches.
    /// </summary>
    public bool ThrowOnUnmatchedHttpRequest { get; set; } = true;

    /// <summary>
    /// Gets or sets the configured test environment name.
    /// </summary>
    [Required]
    [MinLength(1)]
    public string EnvironmentName { get; set; } = "Testing";
}
